name: Robot Framework CI

on:
  push:
    branches:
      - main
      # do not run tests if file README.md changes
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  Run-Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install robotstatuschecker>=1.4
      - name: Run Test
        run: python -m robot --outputdir Results/ Tests/
      - name: Run Robot Framework tests and generate report
        run: |
          echo "ROBOT_RC=$?" >> "$GITHUB_ENV"
      # - name: If Auto Test Pass Rate Not 100%, Job Will Fail
      #   if: env.ROBOT_RC != '0'
      #   run: |
      #     echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
      #     exit 1
      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results
