name: Robot Framework CI

on:
  push:
    branches:
      - main
      # do not run tests if file README.md changes
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  Run-Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install robotstatuschecker>=1.4
      - name: Install Chrome and ChromeDriver
        run: |
          # Fetch the latest ChromeDriver version available
          CHROMEDRIVER_VERSION=$(wget --no-verbose --output-document - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)

          # Download the latest ChromeDriver
          wget --no-verbose --output-document /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip

          # Unzip and set up ChromeDriver
          unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver
          chmod +x /opt/chromedriver/chromedriver
          ln -fs /opt/chromedriver/chromedriver /usr/local/bin/chromedriver

          # Extract the major version of ChromeDriver (e.g., 129 from 129.x.x)
          CHROME_MAJOR_VERSION=$(echo $CHROMEDRIVER_VERSION | cut -d. -f1)

          # Use the ChromeDriver major version to install the corresponding version of Google Chrome
          sudo rm -rf /etc/apt/sources.list.d/google-chrome.list
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list"
          sudo apt-get update

          # Find the closest available version of Google Chrome that matches the ChromeDriver version
          sudo apt-get install -y google-chrome-stable=$CHROME_MAJOR_VERSION.*

          # Check installed versions of Chrome and ChromeDriver
          google-chrome --version
          chromedriver --version
      - name: Run Test
        run: python -m robot --outputdir Results/ Tests/
      - name: Run Robot Framework tests and generate report
        run: |
          echo "ROBOT_RC=$?" >> "$GITHUB_ENV"
      # - name: If Auto Test Pass Rate Not 100%, Job Will Fail
      #   if: env.ROBOT_RC != '0'
      #   run: |
      #     echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
      #     exit 1
      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results
